It looks like these symbols have been moved into the AudioToolbox framework
Undefined symbols for architecture x86_64:
  "_AudioQueueAllocateBuffer", referenced from:
      _audioqueue_thread in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueDispose", referenced from:
      _COREAUDIO_CloseDevice in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueEnqueueBuffer", referenced from:
      _audioqueue_thread in libUrho3D.a(SDL_coreaudio.m.o)
      _inputCallback in libUrho3D.a(SDL_coreaudio.m.o)
      _outputCallback in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueFreeBuffer", referenced from:
      _COREAUDIO_CloseDevice in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueNewInput", referenced from:
      _audioqueue_thread in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueNewOutput", referenced from:
      _audioqueue_thread in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueSetProperty", referenced from:
      _audioqueue_thread in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueStart", referenced from:
      _audioqueue_thread in libUrho3D.a(SDL_coreaudio.m.o)
  "_AudioQueueStop", referenced from:
      _audioqueue_thread in libUrho3D.a(SDL_coreaudio.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)